<?php
use Drupal\Core\Form\FormStateInterface;
/**
 * @file
 * Contains assign_calc.module
 */
const BODY = 'body';
const STEPS = 'steps';
const STEP = 'step';
const PARAGRAPH_NAME = 'step';

function assign_calc_page_attachments(array &$page) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface && $node->getType() == 'assignment' || \Drupal::routeMatch()->getRouteName() == 'example.form') {
    $page['#attached']['library'][] = 'assign_calc/basic';
  }
}


function assign_calc_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id=="contact_message_assignment_planner_feedback_form"){
    $form['subject']['widget'][0]['value']['#default_value'] = "Assignment Planner Feedback";
  }
}

function assign_calc_preprocess_node(&$variables) {
  if ($variables['node']->getType() == 'assignment') {
    $variables['content']['body']['#attributes']['assign_calc'] = BODY;
    $variables['content']['field_steps']['#attributes']['assign_calc'] = STEPS;
    $i = 0;
    while ($variables['content']['field_steps'][$i]) {
      $variables['content']['field_steps'][$i]['#attributes']['assign_calc'] = STEP;
      $variables['content']['field_steps'][$i]['#attributes']['assign_calc_step'] = $i;
      $i++;
    }
  }
}

function assign_calc_preprocess_field(&$variables) {
  if ($variables['element']['#bundle'] === PARAGRAPH_NAME && $variables['entity_type'] == 'paragraph') {
    $variables['attributes']['assign_calc'] = $variables['field_name'];
  }
}
