<?php
use Drupal\Core\Form\FormStateInterface;
/**
 * @file
 * Contains assign_calc.module
 */

function assign_calc_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'assign_calc/basic';
}

function assign_calc_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id=="contact_message_assignment_planner_feedback_form"){
    $form['subject']['widget'][0]['value']['#default_value'] = "Assignment Planner Feedback";
  }

}
