name: CI

on:
  push:
    branches: [ utsc ]
  pull_request:
    branches: [ utsc ]
  workflow_dispatch:

jobs:
  islandora-module-ci:
    uses: digitalutsc/reusable_workflows/.github/workflows/islandora-module-ci.yml@main
    with:
      module_name: assign_calc
      install_chromedriver: true
